-- Postgres 11

CREATE SCHEMA IF NOT EXISTS "PUBLIC";

CREATE TABLE "PUBLIC"."POLICY"(
    "ID" VARCHAR(255) PRIMARY KEY,
    "DISPLAY_NAME" VARCHAR(255),
    "DESCRIPTION" VARCHAR(1000),
    "RAW_POLICY" BLOB,
    "CREATED_AT" TIMESTAMP,
    "UPDATED_AT" TIMESTAMP
);

CREATE TABLE "PUBLIC"."SUITE"(
    "ID" VARCHAR(255) PRIMARY KEY,
    "DISPLAY_NAME" VARCHAR(255),
    "DESCRIPTION" VARCHAR(1000),
    "CREATED_AT" TIMESTAMP,
    "UPDATED_AT" TIMESTAMP
);

CREATE "PUBLIC"."SUITEENTITY_POLICIES"(
    "SUITEENTITY_ID" VARCHAR(255) NOT NULL,
    "POLICIES" VARCHAR(255)
);