version: '3.3'

# Postgres 11 Docker image
services:
  postgres:
    environment:
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: usr
    image: postgres:11-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/mydb/data:rw

volumes:
  postgres: