version: '3.3'
services:
  opa:
    image: openpolicyagent/opa:latest-rootless
    ports:
      - 8181:8181
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"